package com.example.pickme_nebula0;

import android.util.Log;

import com.example.pickme_nebula0.db.DBManager;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.messaging.FirebaseMessaging;
import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.FirebaseFirestore;

/**
 * @author Stephine Yearley
 * This class handles Firestore Cloud Messaging registration and token refresh
 * It is based of code generated by Open AI's ChatGPT in response to prompt:
 * I have an android app written in java in android studio. I am using firestore as my database. I want to generate an android notification for a specific user everytime a new document is created in a specfic collection of the database. I want the user to receive these notifications even if the application on their phone isn't running (e.g. has been fully killed)
 */
public class MyFirebaseMessagingService extends FirebaseMessagingService {
    @Override
    public void onNewToken(String token) {
        super.onNewToken(token);
        Log.d("FCM", "Refreshed FCM token: " + token);

        saveTokenToFirestore(token,DeviceManager.getDeviceId());
    }

    public static void saveTokenToFirestore(String fcmToken, String userID) {
        FirebaseFirestore db = FirebaseFirestore.getInstance();

        db.collection("Users").document(userID)
                .update("fcmToken", fcmToken)
                .addOnSuccessListener(aVoid -> Log.d("Firestore", "FCM token saved successfully"))
                .addOnFailureListener(e -> Log.w("Firestore", "Error saving FCM token", e));
    }

    public static void registerFCMToken(String userID) {
        FirebaseMessaging.getInstance().getToken()
                .addOnCompleteListener(task -> {
                    if (!task.isSuccessful()) {
                        Log.w("FCM", "Fetching FCM token failed", task.getException());
                        return;
                    }

                    String fcmToken = task.getResult();
                    Log.d("FCM", "FCM Token: " + fcmToken);

                    saveTokenToFirestore(fcmToken,userID);
                });
    }
}
