name: Android CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decrypt google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 --decode > ./app/PickMe_nebula0/app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./app/PickMe_nebula0/
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./app/PickMe_nebula0/
    - name: Run Unit Tests
      run: ./gradlew test
      working-directory: ./app/PickMe_nebula0/
